on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2

  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      output_folder: "img"
      parse_args: "totem:'-c 12' totem_de:'-c 12'"
      draw_args: "totem:'-j config/info.json' totem_de:'-j config/info.json'"
      commit_message: "Draw: ${{ github.event.head_commit.message }}"